[pytest]
; addopts = -v -s --tb=short
python_files = test_*.py *_test.py
python_classes = Test* *Test *Suite
python_classes = *suites *test
python_files = *auto.py
markers =
    positive: Тесты, которые проверяют корректное поведение функции
    negative: Тесты, которые проверяют некорректное поведение функции
